version: '3.7'
# list all the containers
services:
  # database
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: toiko
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  toiko:
    build: .
    depends_on:
      - db
